name: Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build Docker image
      run: docker build -t echo_server .
    - name: Run Docker container
      run: docker run -d -p 3000:3000/udp --name echo-server echo_server
    - name: Test Docker container
      run: ./test.sh
    - name: Stop Docker container
      run: docker stop echo-server && docker rm echo-server
