name: Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build Docker image
      run: docker build -t echo_server .
    - name: Run Docker container
      run: |
        docker run -d -p 3000:3000/udp --name echo_server echo_server
        sleep 10  
    - name: Healthcheck
      run: |
        RESPONSE=$(echo "Hello from client" | nc -u localhost 3000)
        if [ "$RESPONSE" != "Hello from client" ]; then
          echo "Healthcheck failed: unexpected response '$RESPONSE'"
          docker stop echo_server && docker rm echo_server
          exit 1
        fi
    - name: Stop Docker container
      run: docker stop echo_server && docker rm echo_server
